# Generated by Django 4.1 on 2023-01-31 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "depart_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="department's name"
                    ),
                ),
                (
                    "num_employ",
                    models.PositiveIntegerField(
                        default=0, null=True, verbose_name="Number of employ"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest",
                    models.IntegerField(null=True, verbose_name="Interest_One"),
                ),
                (
                    "experience",
                    models.IntegerField(null=True, verbose_name="experience_One"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Hr's email"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="first_name"),
                ),
                (
                    "second_name",
                    models.CharField(max_length=30, verbose_name="second_name"),
                ),
                ("password", models.CharField(max_length=64, verbose_name="Password")),
                ("role", models.IntegerField(default=3, verbose_name="Roles")),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="manger's email"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="first name"),
                ),
                (
                    "second_name",
                    models.CharField(max_length=30, verbose_name="second name"),
                ),
                ("password", models.CharField(max_length=64, verbose_name="Password")),
                ("role", models.IntegerField(default=2, verbose_name="Roles")),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="skills_name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Team's name"
                    ),
                ),
                (
                    "team_profile",
                    models.JSONField(null=True, verbose_name="team's profile "),
                ),
                ("ratio", models.FloatField(null=True, verbose_name="Ratio")),
                ("Skill", models.ManyToManyField(to="Assign.skill")),
                (
                    "depart_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Assign.department",
                    ),
                ),
                (
                    "man_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Assign.manager",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Graduate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Graduate's email"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="first name"),
                ),
                (
                    "second_name",
                    models.CharField(max_length=30, verbose_name="second name"),
                ),
                ("password", models.CharField(max_length=64, verbose_name="Password")),
                ("role", models.IntegerField(default=1, verbose_name="Roles")),
                ("Form", models.ManyToManyField(to="Assign.form")),
                (
                    "depart_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Assign.department",
                    ),
                ),
                (
                    "man_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Assign.manager",
                    ),
                ),
                (
                    "team_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Assign.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="form",
            name="Skill_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Skill",
                to="Assign.skill",
            ),
        ),
    ]
