# Generated by Django 4.1 on 2022-11-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "depart_name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="department's name",
                    ),
                ),
                (
                    "num_employ",
                    models.PositiveIntegerField(
                        default=0, null=True, verbose_name="Number of employ"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grad_email",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="grad_email",
                    ),
                ),
                (
                    "form_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Assign.form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Graduate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grad_email",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Graduate's email",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=30, null=True, verbose_name="first name"
                    ),
                ),
                (
                    "second_name",
                    models.CharField(
                        max_length=30, null=True, verbose_name="second name"
                    ),
                ),
                ("password", models.CharField(max_length=64, verbose_name="Password")),
                (
                    "depart_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Assign.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "man_email",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="manger's email",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=30, null=True, verbose_name="first name"
                    ),
                ),
                (
                    "second_name",
                    models.CharField(
                        max_length=30, null=True, verbose_name="second name"
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=64, null=True, verbose_name="Password"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_name",
                    models.IntegerField(
                        null=True, unique=True, verbose_name="team's id "
                    ),
                ),
                (
                    "team_profile",
                    models.IntegerField(null=True, verbose_name="team's id "),
                ),
                (
                    "depart_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Assign.department",
                    ),
                ),
                (
                    "man_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Assign.manager"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Departments",
        ),
        migrations.DeleteModel(
            name="Forms",
        ),
        migrations.DeleteModel(
            name="Graduates",
        ),
        migrations.DeleteModel(
            name="Managers",
        ),
        migrations.RemoveField(
            model_name="hr",
            name="hr_emial",
        ),
        migrations.AddField(
            model_name="hr",
            name="hr_email",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Hr's email"
            ),
        ),
        migrations.AddField(
            model_name="hr",
            name="password",
            field=models.CharField(max_length=64, null=True, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="hr",
            name="first_name",
            field=models.CharField(max_length=30, null=True, verbose_name="first_name"),
        ),
        migrations.AlterField(
            model_name="hr",
            name="second_name",
            field=models.CharField(
                max_length=30, null=True, verbose_name="second_name"
            ),
        ),
        migrations.AddField(
            model_name="graduate",
            name="man_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Assign.manager"
            ),
        ),
        migrations.AddField(
            model_name="graduate",
            name="team_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Assign.team"
            ),
        ),
    ]
