# Generated by Django 4.1 on 2022-11-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="graduate",
            name="token",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="TOKEN"
            ),
        ),
        migrations.AddField(
            model_name="hr",
            name="token",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="TOKEN"
            ),
        ),
        migrations.AddField(
            model_name="manager",
            name="token",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="TOKEN"
            ),
        ),
    ]
