# Generated by Django 4.1 on 2023-02-01 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="man_id",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Assign.manager",
            ),
        ),
    ]
