# Generated by Django 4.1 on 2022-11-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graduate",
            name="token",
        ),
        migrations.RemoveField(
            model_name="hr",
            name="token",
        ),
        migrations.RemoveField(
            model_name="manager",
            name="token",
        ),
    ]
