# Generated by Django 4.1 on 2022-11-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0002_graduate_token_hr_token_manager_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_name",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Team's name"
            ),
        ),
    ]
