# Generated by Django 4.1 on 2023-03-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0003_alter_team_num_positions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="ratio",
            field=models.FloatField(default=0.5, null=True, verbose_name="Ratio"),
        ),
    ]
