# Generated by Django 4.1 on 2022-11-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0003_alter_team_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_profile",
            field=models.CharField(
                max_length=100, null=True, verbose_name="team's profile "
            ),
        ),
    ]
