# Generated by Django 4.1 on 2022-11-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0004_alter_team_team_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="graduate",
            name="role",
            field=models.IntegerField(default=1, verbose_name="Roles"),
        ),
        migrations.AddField(
            model_name="hr",
            name="role",
            field=models.IntegerField(default=3, verbose_name="Roles"),
        ),
        migrations.AddField(
            model_name="manager",
            name="role",
            field=models.IntegerField(default=2, verbose_name="Roles"),
        ),
    ]
