# Generated by Django 4.1 on 2022-11-23 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0006_alter_graduate_depart_id_alter_graduate_man_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="graduate",
            old_name="grad_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="hr",
            old_name="hr_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="manager",
            old_name="man_email",
            new_name="email",
        ),
    ]
