image: node:16.5.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - client/package-lock.json
      prefix: npm
    paths:
      - client/node_modules/
  script:
    - cd "client"
    - npm install
    - npm run build
    - cp -a dist/. ../public/
    - cd ..
  artifacts:
    paths:
      - public
