image: python:3.8-alpine

# Define the pipeline stages
stages:
  - build_test_quality

# Define the backend jobs
backend_build:
  stage: build_test_quality
  before_script:
    # Install dependencies
    - apk add --no-cache build-base
    - pip install --upgrade pip
    - cd "AutoAssign"
    - pip install --no-cache-dir -r requirements.txt
  script:
    # Build the Django backend
    - python manage.py makemigrations
    - python manage.py migrate

backend_test:
  stage: build_test_quality
  needs: [backend_build]
  before_script:
    # Install dependencies
    - apk add --no-cache build-base
    - pip install --upgrade pip
    - cd "AutoAssign"
    - pip install --no-cache-dir -r requirements.txt
  script:
    # Run the Django backend tests
    - python manage.py test

backend_quality:
  stage: build_test_quality
  needs: [backend_build]
  before_script:
    # Install dependencies
    - apk add --no-cache build-base
    - pip install --upgrade pip
    - cd "AutoAssign"
    - pip install --no-cache-dir pylint pylint-django
  script:
    # Run pylint to check for coding style issues and other code quality problems
    - pylint --disable=C0114,C0115,R0903,C0116,E1101,W0105,W0613,E0401 ext
    - cd "Assign"
    - pylint --disable=C0114,C0115,R0903,C0116,E1101,W0105,W0613,E0401,C0302,R0911 views.py
    - pylint --disable=C0114,C0115,R0903,C0116,E1101,W0105,W0613,E0401 serializers.py
    - pylint --disable=C0114,C0115,R0903,C0116,E1101,W0105,W0613,E0401 models.py
    - pylint --disable=C0114,C0115,R0903,C0116,E1101,W0105,W0613,E0401,W0640,W0612,C0301,R0914,C0301 alg.py

  artifacts:
    paths:
      - htmlcov/

backend_coverage:
  stage: build_test_quality
  needs: [backend_test]
  before_script:
    # Install dependencies
    - apk add --no-cache build-base
    - pip install --upgrade pip
    - cd "AutoAssign"
    - pip install --no-cache-dir -r requirements.txt
  script:
    # Run tests with coverage
    - coverage run --source='Assign' manage.py test
    # Generate coverage report in XML format
    - coverage xml
  artifacts:
    reports:
      junit: test-results.xml
    paths:
      - coverage.xml

# Define the frontend jobs
frontend_build:
  stage: build_test_quality
  needs: []
  cache:
    key:
      files:
        - client/package-lock.json
      prefix: npm
    paths:
      - client/node_modules/
  image: node:16.5.0-alpine
  script:
    - cd "client"
    - npm install
    - npm run build
    - cp -a dist/. ../public/
    - cd ..
  artifacts:
    paths:
      - public

frontend_quality:
  stage: frontend_build_test_quality
  image: node:16.5.0
  before_script:
    # Install dependencies
    - cd "client"
    - npm install
    - npm install eslint eslint-plugin-react @typescript-eslint/parser @typescript-eslint/eslint-plugin
  script:
    - npx eslint --ext .tsx --ext .ts